# Generated by Django 5.2.1 on 2025-06-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
        ('users', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_garden',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gardens.garden'),
        ),
        migrations.AddField(
            model_name='user',
            name='peaced_gardens',
            field=models.IntegerField(default=0),
        ),
    ]
