# Generated by Django 5.2.1 on 2025-06-04 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_garden_user_peaced_gardens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
