# Generated by Django 5.2.1 on 2025-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='initial_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='garden',
            name='slug',
            field=models.SlugField(default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='tests',
            field=models.JSONField(default='{}'),
        ),
    ]
