# Generated by Django 5.2.1 on 2025-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_garden_initial_code_garden_slug_garden_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='tests',
            field=models.JSONField(default=dict),
        ),
    ]
