# Generated by Django 5.2.1 on 2025-06-04 20:25

import gardens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_alter_garden_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='tests',
        ),
        migrations.AddField(
            model_name='garden',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='garden',
            name='test_input',
            field=models.FileField(default='', upload_to='garden_test/%Y/%m/%d/%h/%M/%s/%f', validators=[gardens.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='garden',
            name='test_output',
            field=models.FileField(default='', upload_to='garden_test/%Y/%m/%d/%h/%M/%s/%f', validators=[gardens.models.validate_file_extension]),
        ),
    ]
