# Generated by Django 5.2.1 on 2025-06-04 20:32

import django.core.validators
import gardens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_remove_garden_tests_garden_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='garden',
            name='test_input',
            field=models.FileField(default='', unique=True, upload_to='garden_test/%Y/%m/%d/%h/%M/%s/%f', validators=[gardens.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='garden',
            name='test_output',
            field=models.FileField(default='', unique=True, upload_to='garden_test/%Y/%m/%d/%h/%M/%s/%f', validators=[gardens.models.validate_file_extension]),
        ),
    ]
