# Generated by Django 5.2.1 on 2025-06-05 13:24

import gardens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_alter_garden_rating_alter_garden_test_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='test_input',
            field=models.FileField(default='', unique=True, upload_to='garden_test/%Y/%m/%d/%H/%M/%S/', validators=[gardens.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='garden',
            name='test_output',
            field=models.FileField(default='', unique=True, upload_to='garden_test/%Y/%m/%d/%H/%M/%S/', validators=[gardens.models.validate_file_extension]),
        ),
    ]
