# Generated by Django 5.2.1 on 2025-06-05 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_alter_garden_test_input_alter_garden_test_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
