# Generated by Django 5.2.2 on 2025-06-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0008_rename_author_garden_author_id_kyokusenmon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='author_id',
            new_name='author_ref',
        ),
        migrations.RenameField(
            model_name='kyokusenmon',
            old_name='garden_id',
            new_name='garden_ref',
        ),
        migrations.RenameField(
            model_name='kyokusenmon',
            old_name='meditator_id',
            new_name='meditator_ref',
        ),
    ]
